#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not support $ POSIX variable expansion, you'll need to change the script
#       to use a different syntax.
#
#   (2) Put the JDK directory in your environment variable JAVA_HOME.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME="${PRG%"${PRG##*/}"}"
    [ -L "$PRG" ]
do
    PRG="$(readlink "$PRG")"
done
APP_HOME="$(cd "${APP_HOME}." && pwd -P)" || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$QUIET" != true ]; then
        printf '%s\n' "$*" >&2
    fi
} >&2

die() {
    printf '%s\n' "$1" >&2
    exit "$2"
} >&2

#
# Class paths
#

# classpath may be quite long
if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
else
    die "$APP_HOME/gradle/wrapper/gradle-wrapper.jar does not exist"
fi

# application home absolute path
APP_HOME="$(cd "${APP_HOME}" && pwd -P)" || exit

# tempfile and capture exit status
MKTEMP_OUTPUT=$(/bin/mktemp -d 2>/dev/null || /bin/mktemp -d -t gradle-wrapper.XXXX 2>/dev/null)
if [ -z "$MKTEMP_OUTPUT" ]; then
    # fall back for systems that don't have mktemp
    MKTEMP_OUTPUT="$(pwd)/gradle-wrapper.$$"
    mkdir -p "$MKTEMP_OUTPUT"
fi

# trap to clean up
trap 'rm -rf -- "$MKTEMP_OUTPUT"' EXIT

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $(/bin/sh -c 'ulimit -n') in #(
    (*unlimited*)
        ;; #(
    *)
        if [ -w /proc/sys/fs/file-max ]; then
            MAX_FD=$( cat /proc/sys/fs/file-max )
        elif [ -w /proc/sys/kern/maxfilesperproc ]; then
            MAX_FD=$( cat /proc/sys/kern/maxfilesperproc )
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...extraoptions
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys"; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg in "$@"; do
        if
            case $arg in #(
            -*)
                false
                ;; # don't mess with options #(
            /?*)
                t=${arg#/} cygpath --windows "/$$t"
                ;; # looks like a path #(
            *)
                echo "$arg"
                ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        set -- "$@" "$arg"
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"
